server:
  port: 8086
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 124.222.45.111
    username: guest
    password: guest
    virtual-host: /emp

leyou:
  sms:
    accessKeyId: LTAIc259TULYzaS7
    accessKeySecret: 1uh79I1UAmwQ4YWsSmOgxw7JEBGA0v
    signName: 乐优商城
    verifyCodeTemplate: SMS_148614415
